Adding test file for retailers api and changing the api from v3 to v4
dreambits/python-bol-api pull request #36
Opened 2021-01-29 07:04 UTC by bharti-dreambits

Adding test file for retailers api and changing the api from v3 to v4

2021-01-29 07:23 UTC, karan-dreambits commented on tests/test_retailer.py
> +        def order_by_id_stub(url, request):
So this is an inner function ?

2021-01-29 07:23 UTC, karan-dreambits commented on tests/test_retailer.py
> +            assert orById.shipmentDetails['pickUpPointName'] == "Albert Heijn: UTRECHT"
Are these tests passing ?

2021-01-29 07:29 UTC, bharti-dreambits commented on tests/test_retailer.py
> +            assert orById.shipmentDetails['pickUpPointName'] == "Albert Heijn: UTRECHT"
Yes sir

2021-01-29 07:31 UTC, bharti-dreambits commented on tests/test_retailer.py
> +        def order_by_id_stub(url, request):
Yes sir, I was it in test_plaza.py file and I found this way more relatable

2021-07-27 10:55 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def handleReturnItem(self, rmaId, status_reason, qty):
@bharti-dreambits @devang-dreambits  Is this related to return items fetching ?

2021-07-27 10:59 UTC, karan-dreambits requested changes

2021-07-27 10:59 UTC, karan-dreambits commented on bol/retailer/models.py
> +class Visibles(ModelList):
Rename this to VisibleCountriesCodes

2021-07-27 10:59 UTC, karan-dreambits commented on bol/retailer/models.py
> +class Visible(Model):
Rename this to VisibleCountryCode

2021-07-27 10:59 UTC, karan-dreambits commented on bol/retailer/models.py
> +# class Price(Model):
Are we going to use this commented model anywhere further ? 
If not then can you remove this ?

2021-07-27 12:26 UTC, bharti-dreambits commented on bol/retailer/api.py
> +    def handleReturnItem(self, rmaId, status_reason, qty):
Yes sir these changes are related to "returns"

2021-07-27 12:42 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def handleReturnItem(self, rmaId, status_reason, qty):
how come this are already in this PR before you even started working on it ?

2021-07-27 12:48 UTC, bharti-dreambits commented on bol/retailer/api.py
> +    def handleReturnItem(self, rmaId, status_reason, qty):
This PR was firstly for v3 to v4. May be because of that we can see the above code in this PR

2021-07-28 08:08 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def handleReturnItem(self, rmaId, status_reason, qty):
Okay

2021-09-02 07:20 UTC, karan-dreambits commented on bol/retailer/api.py
> +        process_id_dict = {}
The way this is coded looks quite complex and unnecessary extra lines. 

I think we can simplify it to something like this:
```
        process_id_dict = {
               "processStatusQueries" : []
        }
        process_statuses = process_id_dict["processStatusQueries"]
        for process_id in process_ids:
            process_statuses.append({"processStatusId" : process_id})

        resp = self.request("POST", json=process_id_dict)
        return ProcessStatuses.parse(self.api, resp.text)
```

right ?

2021-09-02 07:51 UTC, bharti-dreambits commented on bol/retailer/api.py
> +        process_id_dict = {}
Yes, you are right

2021-09-09 15:14 UTC, merged