[ADD] Added functions and models for Shipping Label and FBB Endpoints
dreambits/python-bol-api pull request #39
Opened 2021-10-21 13:20 UTC by bharti-dreambits

2021-11-30 12:12 UTC, karan-dreambits requested changes

2021-11-30 12:12 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def pickupTimeSlots(self,address, numberOfLoadCarriers):
Is this method used in the current flow we are going to work on with Odoo ?

2021-11-30 12:12 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def productLabels(self, labelFormat, products):
what is the purpose of this function ? Either it gets or posts/creates a productLabel, right ? 
If so then the name of function is ambiguous. 
ideally it should be getProductLabels

2021-11-30 12:12 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def loadCarrierLabels(self, replenishment_id, label_type="WAREHOUSE"):
same as above. Function name is ambiguous

2021-11-30 13:20 UTC, bharti-dreambits commented on bol/retailer/api.py
> +    def productLabels(self, labelFormat, products):
Ok sir will change the name

2021-11-30 13:20 UTC, bharti-dreambits commented on bol/retailer/api.py
> +    def loadCarrierLabels(self, replenishment_id, label_type="WAREHOUSE"):
Will change the function name to more meaningful

2021-11-30 13:24 UTC, karan-dreambits commented on bol/retailer/api.py
> +    def pickupTimeSlots(self,address, numberOfLoadCarriers):
so this is not going to be used in the current worklow, right ? 
What is the purpose of this endpoint/feature ?

2022-01-10 18:27 UTC, karan-dreambits approved these changes

2022-01-10 19:14 UTC, merged